server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PWD:mysecretpassword}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rinha}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 300_000
      maximum-pool-size: 6
      minimum-idle: 6
