server:
  port: ${SERVER_PORT:9999}

spring:
  r2dbc:
    username: ${DB_USER:postgres}
    password: ${DB_PWD:mysecretpassword}
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rinha}
